network/urls.py
from django.urls import path

from . import views

app_name = 'network'
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile/<int:pk>", views.profile, name="profile"),
    path('follow/<int:pk>', views.follow, name="follow"),
    path('following', views.following, name="following"),

    # API routes
    path('edit/<int:pk>', views.edit, name="edit"),
    path('like/<int:pk>', views.like, name="like")

]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class Post(models.Model):
    content = models.TextField(null=True)
    poster = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    liked_by = models.ManyToManyField(User, blank=True, related_name='liked')

    def __str__(self):
        return f"{self.poster} posted {self.content}"

class Follow(models.Model):
    following = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="following")
    followed_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name="followed_by")

    def __str__(self):
        return f'{self.following} followed by {self.followed_by}'

network/forms.py
from django.forms import ModelForm
from .models import Post

class NewPostForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({"class": "form-control",
                                                    "rows": 5})

    class Meta:
        model = Post
        fields = ['content']

network/views.py
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from rest_framework.decorators import api_view

from .forms import NewPostForm
from .models import Follow, Post, User
from .serializers import PostSerializers


def index(request):
    posts = Post.objects.all().order_by("-created_at")
    new_post_form = NewPostForm()

    # Apply paginaiton to posts
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    posts_view = paginator.get_page(page_number)

    # Save new post
    if request.method == "POST":
        new_post_form = NewPostForm(request.POST)
        if new_post_form.is_valid():
            new_post = new_post_form.save(commit=False)
            new_post.poster = request.user
            new_post.save()
            return HttpResponseRedirect(reverse("network:index"))

        # Error validation in new post
        else:
            return render(
                request,
                "network/index.html",
                {
                    "new_post_form": new_post_form,
                    "posts": posts_view,
                    "message": "Invalid Post",
                },
            )

    # Display all posts
    return render(
        request,
        "network/index.html",
        {"new_post_form": new_post_form, "posts": posts_view},
    )


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(
                request,
                "network/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(
                request, "network/register.html", {"message": "Passwords must match."}
            )

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(
                request, "network/register.html", {"message": "Username already taken."}
            )
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")


@login_required(login_url="network:login")
def profile(request, pk):

    # Get user profile details
    viewed_user = User.objects.get(pk=pk)
    current_user = request.user
    user_following = Follow.objects.filter(followed_by=current_user).values_list(
        "following", flat=True
    )
    posts = Post.objects.filter(poster=viewed_user)

    # Apply paginaiton to posts
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    posts_view = paginator.get_page(page_number)

    return render(
        request,
        "network/profile.html",
        {
            "viewed_follower_count": Follow.objects.filter(
                following=viewed_user
            ).count(),
            "viewed_following_count": Follow.objects.filter(
                followed_by=viewed_user
            ).count(),
            "user_following": user_following,
            "viewed_user": viewed_user,
            "posts": posts_view,
        },
    )


@login_required(login_url="network:login")
def follow(request, pk):
    viewed_user = User.objects.get(pk=pk)
    current_user = request.user

    # Follow or unfollow user
    if request.method == "POST":
        if "follow" in request.POST:
            new_follow = Follow.objects.create(
                following=viewed_user, followed_by=current_user
            )
            new_follow.save()
        else:
            follow = Follow.objects.get(following=viewed_user, followed_by=current_user)
            follow.delete()

    return HttpResponseRedirect(reverse("network:profile", kwargs={"pk": pk}))


@login_required(login_url="network:login")
def following(request):

    # Show only following posts
    follow = Follow.objects.filter(followed_by=request.user).values_list("following")
    new_post_form = NewPostForm()

    # Apply paginaiton to posts
    posts = Post.objects.filter(poster__in=follow).order_by("-created_at")
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    posts_view = paginator.get_page(page_number)

    return render(
        request,
        "network/index.html",
        {"posts": posts_view, "new_post_form": new_post_form},
    )


@login_required(login_url="network:login")
@api_view(["GET", "PUT"])
def edit(request, pk):

    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == "PUT":
        # Validate user
        if request.user == post.poster:

            # Get data
            data = json.loads(request.body)

            # Serialize and save data
            serializer = PostSerializers(post, data=data, partial=True)
            if serializer.is_valid():
                serializer.save()
                return JsonResponse(serializer.data)
            return JsonResponse(serializer.errors, status=400)

        return JsonResponse({"error": "User not authorized"}, status=401)

    # Send post value
    elif request.method == "GET":
        serializer = PostSerializers(post)
        return JsonResponse(serializer.data, status=200)


@login_required
@api_view(["PUT"])
def like(request, pk):
    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        return HttpResponse(status=404)

    data = json.loads(request.body)

    # Add or remove user from post
    if data.get("liked"):
        post.liked_by.add(request.user)
        post.likes = post.liked_by.all().count()
        post.save()

    else:
        post.liked_by.remove(request.user)
        post.likes = post.liked_by.all().count()
        post.save()

    # Send value
    serializer = PostSerializers(post)
    return JsonResponse(serializer.data, status=200)

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}

    {% if message %}
    <div class="warpper">
        {{ message }}
    </div>
    {% endif %}
    {% if user.is_authenticated %}
    <div class="wrapper">
        <h2>
            New Post
        </h2>
        <form action="{% url 'network:index' %}" method="post">
            {% csrf_token %}
            {{ new_post_form }}
            <button id="new-post" class="btn-sm btn-primary" type="submit">Post</button>
        </form>
    </div>
    {% endif %}
    {% for post in posts %}
    <div class="wrapper" data-value="{{ post.id }}">
        <div class="post-edit-form" style="display: none;">
            <textarea name="edit" id="edit-box" class="edit-text form-control" cols="30" rows="5"></textarea>
            <button id="save-btn" class="btn-sm btn-outline-primary">Save</button>
        </div>
        <div class="post-body">
            <a href="{% url 'network:profile' post.poster.id %}">
                <h3>{{ post.poster }}</h3>
            </a>
            <div class="post-content">
                {{ post.content }}
            </div>
            {% if post.poster == user %}
                <button id="edit-button" class="btn-sm btn-outline-primary" value="{{ post.id }}">Edit</button>
            {% endif %}
        </div>
        <div class="post-details">
            <p class="created">{{ post.created_at }}</p>
            <p id="likes-amount">Likes: {{ post.likes }}</p>
            {% if user.is_authenticated %}
                {% if user in post.liked_by.all %}
                    <p><a class="like" href="#" onclick="return false;">Unlike</a></p>
                {% else %}
                    <p><a class="like" href="#" onclick="return false;">Like</a></p>
                {% endif %}
            {% endif %}
        </div>
    </div>
    {% empty %}
    <div class="wrapper">
        <strong>No Posts</strong>
    </div>
    {% endfor %}


    <nav aria-label="paginate" class="paginate">
        <ul class="pagination">
        {% if posts.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}"> < </a></li>
        {% endif %}
        {% if posts %}
            {% for page in posts.paginator.page_range %}
                {% if posts.number == page %}
                    <li id="pages" class="page-item active"><a class="page-link" href="?page={{ page }}"> {{ page }} </a></li>
                {% else %}
                    <li id="pages" class="page-item"><a class="page-link" href="?page={{ page }}"> {{ page }} </a></li>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% if posts.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}"> > </a></li>
        {% endif %}
        </ul>
    </nav>
    
    {% csrf_token %}
    <script src="{% static 'network/index.js' %}"></script>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'network:index' %}">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:profile' user.id %}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:following'%}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

{% endblock %}

network/templates/network/profile.html
{% extends 'network/layout.html' %}
{% load static %}

{% block body %}

<div class="wrapper">
    <h2>{{ viewed_user }}</h2>
    <p>Followers: {{ viewed_follower_count }}</p>
    <p>Following: {{ viewed_following_count }}</p>

    {% if viewed_user != user %}
        <form action="{% url 'network:follow' viewed_user.id %}" method="post">
            {% csrf_token %}
            {% if viewed_user.id in user_following %}
                <button class="btn-warning" name="unfollow" type="submit">Unfollow</button>
            {% else %}
                <button class="btn-primary" name="follow" type="submit">Follow</button>
            {% endif %}
        </form>
    {% endif %}
</div>

{% for post in posts %}
    <div class="wrapper" data-value="{{ post.id }}">
        <div class="post-edit-form" style="display: none;">
            <textarea name="edit" id="edit-box" class="edit-text form-control" cols="30" rows="5"></textarea>
            <button id="save-btn" class="btn-sm btn-outline-primary">Save</button>
        </div>
        <div class="post-body">
            <a href="{% url 'network:profile' post.poster.id %}">
                <h3>{{ post.poster }}</h3>
            </a>
            <div class="post-content">
                {{ post.content }}
            </div>
            {% if post.poster == user %}
                <button id="edit-button" class="btn-sm btn-outline-primary" value="{{ post.id }}">Edit</button>
            {% endif %}
        </div>
        <div class="post-details">
            <p class="created">{{ post.created_at }}</p>
            <p id="likes-amount">Likes: {{ post.likes }}</p>
            {% if user.is_authenticated %}
                {% if user in post.liked_by.all %}
                    <p><a class="like" href="#" onclick="return false;">Unlike</a></p>
                {% else %}
                    <p><a class="like" href="#" onclick="return false;">Like</a></p>
                {% endif %}
            {% endif %}
        </div>
    </div>
    {% empty %}
    <div class="wrapper">
        <strong>No Posts</strong>
    </div>
{% endfor %}

<nav aria-label="paginate" class="paginate">
    <ul class="pagination">
    {% if posts.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}"> < </a></li>
    {% endif %}
    {% if posts %}
        {% for page in posts.paginator.page_range %}
            {% if posts.number == page %}
                <li id="pages" class="page-item active"><a class="page-link" href="?page={{ page }}"> {{ page }} </a></li>
            {% else %}
                <li id="pages" class="page-item"><a class="page-link" href="?page={{ page }}"> {{ page }} </a></li>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if posts.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}"> > </a></li>
    {% endif %}
    </ul>
</nav>

{% csrf_token %}
<script src="{% static 'network/index.js' %}"></script>

{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>

{% endblock %}